CREATE TABLE test.BOOK (
  ID INT NOT NULL AUTO_INCREMENT,
  BOOK_TITLE VARCHAR(255) NOT NULL,
  BOOK_DESCRIPTION TEXT NOT NULL,
  BOOK_AUTHOR VARCHAR(255) NOT NULL,
  BOOK_ISBN VARCHAR(255) NOT NULL,
  BOOK_PRINT_YEAR INT NOT NULL,
  BOOK_READ_ALREADY BOOLEAN NOT NULL DEFAULT FALSE,
PRIMARY KEY (ID))

ENGINE =  InnoDB
